# Generated by Django 2.0.6 on 2018-10-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0003_usersetup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersetup',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='usersetup',
            name='lastName',
        ),
        migrations.AddField(
            model_name='usersetup',
            name='email',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
    ]
